version: "3.3"

services:
  komga:
    image: ghcr.io/gotson/komga:1.11.0
    container_name: komga
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${KOMGA_DATA_DIR}:/data
    user: "${KOMGA_USER_ID}:${KOMGA_USER_ID}"
    environment:
      - TZ=${TZ}
    ports:
      - ${APP_PORT}:25600
    networks:
      - tipi_main_network
    restart: unless-stopped
