version: "0.5"

services:
  caddy:
    container_name: caddy
    image: caddy:2.7.6
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    privileged: true
    ports:
      - ${APP_PORT}:80
      - ${APP_PORT}:443
      - ${APP_PORT}:443/udp
    volumes:
      - ${APP_DATA_DIR}:/etc/caddy
      - ${APP_DATA_DIR}/site:/srv
      - ${APP_DATA_DIR}/data:/data
      - ${APP_DATA_DIR}/config:/config
    networks:
      - tipi_main_network

