version: "3.7"

services:
  caddy:
    image: caddy:2.7.6
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    privileged: true
    network_mode: host
    ports:
      - ${APP_PORT}:80
      - ${APP_PORT}:443
      - ${APP_PORT}:443/udp
    volumes:
      - ${APP_DATA_DIR}/$PWD/Caddyfile:/etc/caddy/Caddyfile
      - ${APP_DATA_DIR}/$PWD/site:/srv
      - ${APP_DATA_DIR}/caddy_data:/data
      - ${APP_DATA_DIR}/caddy_config:/config
    networks:
      - tipi_main_network

volumes:
  ${APP_DATA_DIR}/caddy_data:
    external: true
  ${APP_DATA_DIR}/caddy_config:
